services:
  smtp-server:
    image: mailhog/mailhog:v1.0.1
    container_name: morrison-smtp-dev
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

  sftp-server:
    image: atmoz/sftp
    platform: linux/amd64
    container_name: morrison-sftp-dev
    restart: unless-stopped
    command: logistica:password:1001
    ports:
      - "2222:22"
    volumes:
      - ./invoices:/home/logistica/invoices